### ISSUE TITLE
Different styles for scroll bar on different browsers

### ISSUE THREAD

**Issue by astaja** [Bekerina/socket.io-chat-app#10]
1. Launch the website "http://chat.bekerina.com:3000/" on the browser Google Chrome (Version 80.0.3987.149 (Official Build) (64-bit)) and Mozilla Firefox (Version 74.0 (64-bit))
2. Check the style used for scroll bar on both browser
3. Check if it is the same

Expected result: styles are the same
Actual result: styles are different on different browsers

![Screenshot from 2020-03-19 20-54-02](https://user-images.githubusercontent.com/55666410/77104139-304de680-6a24-11ea-9885-ba4950553aec.png)

**Comment by Bekerina** [comment]
Thanks for the comment, I am trying to find an answer to this issue. I have founded one solution to customize the scroll bar, but it only works on chrome, so I think I will ask a mentor about this too.

**Comment by janoszen** [comment]
This may not be a bug, it's just how browsers work.
