### ISSUE TITLE
No scroll bar on mobile device

### ISSUE THREAD

**Issue by astaja** [Bekerina/socket.io-chat-app#13]
1. Launch the website "http://chat.bekerina.com:3000/" on a mobile device on the browser Safari (iOS 13.3.1).
2. Touch the screen of your mobile device so the scroll bar is visible

Expected result: the scroll bar appears on the right scan column
Actual result: no scroll bar appears

![Screenshot from 2020-03-23 21-27-58](https://user-images.githubusercontent.com/55666410/77355498-34904180-6d4d-11ea-9452-f1e9e4c6b3d6.png)

**Comment by Bekerina** [comment]
Thanks for the observation. In my mobile device scroll bar appears while scrolling. 
However I don't think the scroll bar in mobile devices is that important. I have examined some chats, and in the mobile version, there are no scroll bars.

![Screenshot_20200405_160455_com android chrome](https://user-images.githubusercontent.com/54816507/78499275-5a0f4900-7758-11ea-8143-fbac463385df.jpg)
