### ISSUE TITLE
Failed to load image

### ISSUE THREAD

**Issue by Bekerina** [Bekerina/socket.io-chat-app#18]
1. Launch the website "http://chat.bekerina.com:3000/" on the browser Google Chrome Version 80.0.3987.149 (Official Build) (64-bit))
2. At the page bottom at the right side of the message input there is a box with no icon.

Expected result: box with an icon
Actual result: box without an icon. (console says: Failed to load resource: the server responded with a status of 404 (Not Found)).

![emoji-icon](https://user-images.githubusercontent.com/54816507/78503891-2b05d100-7772-11ea-88d7-74ba392a0b49.jpg)

**Comment by ShaneLee** [comment]
If you move the image folder to public it will solve this issue. 

Or you could add app.use(express.static('image')) on line 21 in index.js, but then you'd have to alter the image link to just 'hypnotized.png' as opposed to 'image/hypnotized.png'

**Comment by Bekerina** [comment]
@ShaneLee thanks for the advice, it helped :) I moved image folder to the public as you said and it works :)

**Comment by ShaneLee** [comment]
Glad to have helped.

**Comment by janoszen** [comment]
@ShaneLee let me also thank you for helping out. I'm mentoring @Bekerina and @astaja, and this is the project we are building, so I'm kind of curious: how did you find it?

**Comment by ShaneLee** [comment]
I was looking around on the GitHub issues page - came across this project and saw what the issue was likely to be. I've seen similar issues before like this.

**Comment by janoszen** [comment]
Thank you @ShaneLee, we are trying this to be a model project. Feel free to stick around and observe. :)
