### ISSUE TITLE
Input field values presence

### ISSUE THREAD

**Issue by astaja** [Bekerina/socket.io-chat-app#5]
1. Launch the website "http://chat.bekerina.com:3000/" on the browser Google Chrome (Version 80.0.3987.149 (Official Build) (64-bit))
2. Enter values in both input fiels
3. Press "Enter" or click "Send" button
4. Check if values from both input fields disappeared

Expected result: values disappear from both input fields
Actual result: values do not disappear from the upper input field

![Screenshot from 2020-03-19 19-54-28](https://user-images.githubusercontent.com/55666410/77099057-009ae080-6a1c-11ea-9e15-1520a21d5a0a.png)

**Comment by Bekerina** [comment]
Thanks, for comment, but I think upper input field value - the name, should not disappear after the send button is clicked, because it will be very uncomfortable to write your name every time you want to send a message.
