### ISSUE TITLE
Input field values appearance_2

### ISSUE THREAD

**Issue by astaja** [Bekerina/socket.io-chat-app#8]
1. Launch the website "http://chat.bekerina.com:3000/" on the browser Mozilla Firefox (Version 74.0 (64-bit))
2. Enter values in both input fiels
3. Press "Enter" or click "Send" button
4. Check if values from both input fields disappeared

Expected result: values disappear from both input fields
Actual result: values do not disappear from the upper input field

![Screenshot from 2020-03-19 20-40-51](https://user-images.githubusercontent.com/55666410/77102766-04c9fc80-6a22-11ea-896b-94ea5a55e2c6.png)

**Comment by Bekerina** [comment]
Thanks, for comment, but I think upper input field value - the name, should not disappear after the send button is clicked, because it will be very uncomfortable to write your name every time you want to send a message.
