### ISSUE TITLE
Different style colors on different browsers

### ISSUE THREAD

**Issue by astaja** [Bekerina/socket.io-chat-app#9]
1. Launch the website "http://chat.bekerina.com:3000/" on the browser Google Chrome (Version 80.0.3987.149 (Official Build) (64-bit)) and Mozilla Firefox (Version 74.0 (64-bit))
2. Check if the same color is used on both browsers as a website style

Expected result: same color is used on every browser
Actual result: different colors are displayed on different browsers

![Screenshot from 2020-03-19 20-49-03](https://user-images.githubusercontent.com/55666410/77103712-83736980-6a23-11ea-9af2-f4a435333a64.png)

**Comment by Bekerina** [comment]
Hmm, strange... in my monitor, colors are the same. So maybe this is the computer/monitor settings issue? I can't find an answer in google, so perhaps I will ask a mentor to help with this :) 

![image](https://user-images.githubusercontent.com/54816507/77849523-e1970e00-71d4-11ea-8732-886aba45bd6d.png)

**Comment by janoszen** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=44872
